# Generated by Django 4.1 on 2022-08-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=2000)),
                ('tag', models.CharField(max_length=250)),
                ('publish_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
